languageCode = "en-us"
contentdir = "content"
publishdir = "docs"
builddrafts = false
baseUrl = "http://example.org"
canonifyurls = true
title = "Ace Eldeib"
author = "Ace Eldeib"
theme = "bootstrap"
