languageCode = "en-us"
contentdir = "content"
publishdir = "docs"
builddrafts = false
baseUrl = "https://alexeldeib.xyz"
canonifyurls = true
title = "Ace Eldeib"
author = "Ace Eldeib"
theme = "bootstrap"
