author = "Ace Eldeib"
baseUrl = "https://alexeldeib.xyz"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-us"
publishdir = "docs"
theme = "bootstrap"
title = "Ace Eldeib"
